spring:
  profiles: native
  application:
    name: configuracao
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

spring.cloud.config.server.native.searchLocations: file:///Users/fabricio.jacob/Documents/repositorios/curso/config-repo

management:
  endpoints:
    web:
      exposure:
        include:
          - bus-refresh
server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      registryFetchIntervalSeconds: 5

---
spring:
  profiles: docker
  cloud:
    config:
      server:
        native:
          search-locations:
            - file:/config-repo
  rabbitmq:
    host: rabbitmq

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
      registryFetchIntervalSeconds: 5

