spring:
  application:
    name: configuracao
  cloud:
    config:
      server:
        native:
          search-locations:
            - file:${PWD}/config-repo
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include:
          - bus-refresh
server:
  port: 8888

---
spring:
  profiles: docker
  cloud:
    config:
      server:
        native:
          search-locations:
            - file:/config-repo
  rabbitmq:
    host: rabbitmq

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
      registryFetchIntervalSeconds: 5

server:
  port: 8888
