spring:
  application:
    name: configuracao
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fabriciolfjacob/configuracao.git
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
      registryFetchIntervalSeconds: 5

management:
  endpoints:
    web:
      exposure:
        include:
          - bus-refresh
server:
  port: 8888
