app:
  discovery: localhost
  rabbitmq: localhost
  mysql: localhost
  

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.discovery}:8761/eureka
      registryFetchIntervalSeconds: 5
      
spring:
  application:
    name: clientes
  datasource:
    url: jdbc:mysql://${app.mysql}:3306/cadastro?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
  rabbitmq:
    host: ${app.rabbitmq}
    port: 5672
    username: guest
    password: guest      
  
management:
  endpoints:
    web:
      exposure:
        include: "*"


---
spring.profiles: docker
app:
  discovery: eureka
  rabbitmq: rabbitmq
  mysql: mysql
  