app:
  discovery: localhost
  rabbitmq: localhost
  mongodb: localhost
  

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.discovery}:8761/eureka
      registryFetchIntervalSeconds: 5
      
spring:
  data:
    mongodb:
      uri: mongodb://${app.mongodb}:27017/curso
  rabbitmq:
    host: ${app.rabbitmq}
    port: 5672
    username: guest
    password: guest      
  
management:
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j.retry:
  backends:
    product:
      maxRetryAttempts: 3
      waitDuration: 1000
      retryExceptions:
      - org.springframework.web.reactive.function.client.WebClientResponseException$InternalServerError

resilience4j.circuitbreaker:
  backends:
    product:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 5
      failureRateThreshold: 50
      waitInterval: 10000
      maxRetryAttempts: 3 #maximo de 3 tentativas
      waitDuration: 1000 #espera de 1 segundo a cada tentativa
      ringBufferSizeInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      retryExceptions:
        - org.springframework.web.reactive.function.client.WebClientResponseException$InternalServerError #excecao que dispara o try   


---
spring.profiles: docker
app:
  discovery: eureka
  rabbitmq: rabbitmq
  mongodb: mongo  