spring:
  application:
    name: turbine
server:
  port: 9999
turbine:
  clusterNameExpression: new String('default')
  appConfig: produtos, clientes
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
