ribbon.NFLoadBalancerPingInterval: 5
ribbon.ServerListRefreshInterval: 5000

app.eureka: localhost
server:
  port: 8443
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: eureka-api
          uri: http://${app.eureka}:8761
          predicates:
            - Path=/eureka/api/{segment}
          filters:
            - SetPath=/eureka/{segment}

        - id: eureka-web-start
          uri: http://${app.eureka}:8761/eureka
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/

        - id: eureka-web-other
          uri: http://${app.eureka}:8761
          predicates:
            - Path=/eureka/**

        - id: clientespf
          uri: lb://clientes/pf
          predicates:
            - Path=/pf

        - id: clientespj
          uri: lb://clientes/pj
          predicates:
            - Path=/pj

        - id: produtos
          uri: lb://produtos
          predicates:
            - Path=/produtos/**

        - id: faturamento
          uri: lb://faturamento
          predicates:
            - Path=/faturamento/**

        - id: recomendacao
          uri: lb://recomendacao
          predicates:
            - Path=/recomendacao/**

eureka:
  client:
    service-url:
      registryFetchIntervalSeconds: 5
      defaultZone: "http://${app.eureka}:8761/eureka/"

---
spring.profiles: docker

app.eureka: eureka